apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pre-analysis-template
  namespace: app
spec:
  args:
    - name: service-name
  metrics:
    - name: webmetric
      initialDelay: 30s
      failureLimit: 2
      interval: 10s
      count: 3
      successCondition: result == "healthy"
      provider:
        web:
          url: "http://{{ args.service-name }}.app.svc.cluster.local:8080/sample_api"
          jsonPath: "{$.status}"
